name: Java Maven Build

# Trigger the workflow on push or pull request events
on:
  push:
    branches:
      - master
      - 'feature/*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK (Java Development Kit)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11' # Specify Java version (11 is a common choice)
          distribution: 'adoptopenjdk' # Use AdoptOpenJDK (or other like Zulu, OpenJDK, etc.)
      
      # Cache Maven dependencies to speed up future builds
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build and test the project with Maven
      - name: Build with Maven
        run: mvn clean install -B # -B skips the interactive mode

      # Optionally, you can also run additional tests or deploy here
      # For example, if you have integration tests
      # - name: Run integration tests
      #   run: mvn verify -P integration-tests

      # Optionally, you can deploy to a server or repository (e.g., Maven Central, Nexus, etc.)
      # - name: Deploy to Maven repository
      #   run: mvn deploy -DskipTests
